version: "3"
services:
  redis:
    image: redis:latest
    container_name: voting-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: voting-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votesdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build: ./worker
    container_name: voting-worker
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      

  result:
    build: ./result
    container_name: voting-result
    expose:
      - "8081"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: voting-frontend
    expose:
      - "8080"
    depends_on:
      - redis
      - result

  backend:
    build: ./backend
    container_name: voting-backend
    expose:
      - "5000"
    depends_on:
      - redis
      - postgres

  nginx:
    image: nginx:latest
    container_name: voting-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - result
